language: node_js
node_js:
- node
env:
  global:
    secure: ***REMOVED***
cache:
  directories:
  - node_modules
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- '[ -e "./cc-test-reporter" ] || curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter'
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- commitlint-travis
- npm test
after_script:
- greenkeeper-lockfile-upload
- npm run coverage
- codecov
- ./cc-test-reporter after-build --coverage-input-type lcov --debug --exit-code $TRAVIS_TEST_RESULT
