apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      volumes:
        - name: passwd
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: passwd
              path: passwd
        - name: group
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: group
              path: group
        - name: shadow
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: shadow
              path: shadow
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 256M
        - name: shinyserver
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: shiny-server.conf
              path: shiny-server.conf
        - name: rserverconf
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: rserver.conf
              path: rserver.conf
        - name: rsessionconf
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: rsession.conf
              path: rsession.conf
        - name: renviron
          configMap:
            name: {{ template "fullname" . }}
            items:
            - key: .Renviron
              path: .Renviron
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.existingClaim }}
		{{ end }}
      hostname: {{ template "fullname" . }}
      securityContext:
        runAsNonRoot: true
        fsGroup: {{ .Values.gid }}
        {{ $firstGroup := .Values.supplementalGroups | first }}
        {{- if $firstGroup.gid }}
        supplementalGroups:
          {{- range .Values.supplementalGroups }}
          - {{ .gid }}
          {{- end }}
        {{- end }}
      containers:
      - name: rstudio-server
        image: {{ .Values.advanced.dockerImage }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 8787
        - containerPort: 3838
        livenessProbe:
          httpGet:
            path: /unsupported_browser.htm
            port: 8787
          initialDelaySeconds: 30
          timeoutSeconds: 30
        securityContext:
          runAsUser: {{ .Values.uid }}
          runAsGroup: {{ .Values.gid }}
        env:
        - name: TZ
          value: America/Chicago
        - name: USER
          value: {{ .Values.username }}
        - name: USERNAME
          value: {{ .Values.username }}
        - name: HOME
          value: /home/rstudio
        {{- if ne .Values.persistentStorage.existingClaim "" }}
        - name: SHINY_APPS_PATH
          value: /mnt/{{ .Values.persistentStorage.existingClaimName }}/.tools/{{ template "fullname" . }}/shiny-server
        - name: PVC_MOUNT_PATH
          value: /mnt/{{ .Values.persistentStorage.existingClaimName }}
        {{- end }}
        volumeMounts:
        - name: passwd
          mountPath: /etc/passwd
          subPath: passwd
        - name: group
          mountPath: /etc/group
          subPath: group
        - name: shadow
          mountPath: /etc/shadow
          subPath: shadow
        - name: shm
          mountPath: /dev/shm
        - name: shinyserver
          mountPath: /etc/shiny-server/shiny-server.conf
          subPath: shiny-server.conf
        - name: rserverconf
          mountPath: /etc/rstudio/rserver.conf
          subPath: rserver.conf
        - name: rsessionconf
          mountPath: /etc/rstudio/rsession.conf
          subPath: rsession.conf
        - name: renviron
          mountPath: /home/rstudio/.Renviron
          subPath: .Renviron
        {{- if ne .Values.persistentStorage.existingClaim "" }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
          mountPropagation: HostToContainer
          readOnly: {{ .Values.persistentStorage.readOnly }}
          {{ if ne .Values.persistentStorage.subPath "/" }}
          subPath: {{ .Values.persistentStorage.subPath }}
          {{ end }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /home/{{ .Values.username }}
          mountPropagation: HostToContainer
          readOnly: {{ .Values.persistentStorage.readOnly }}
          subPath: home/{{ .Values.username }}
        {{- end }}

