# Open this with mermaid live editor https://mermaidjs.github.io/mermaid-live-editor/

graph TD
C[Control]

C-->Ca[Differential drive]
Ca-->Cb[Motor driver]
Cb-->Cc[Left / right motors]

Eb[5V supply powers everything]
