@startuml Devices


node switch as "unmanaged switch"

frame picluster {
    node pi1 {
        [zwavejs2mqtt]
        [etcd1]
    }
    node pi2 {
        [pikvm]
        [etcd2]
    }
}

frame tinycluster {
    node tiny1 {
        [etcd3]
        [control1]
        [worker1]
    }
    node tiny2 {
        [control2]
        [worker2]
    }
    node tiny3 {
        [control3]
        [worker3]
    }
}

picluster -[hidden]- tinycluster

switch - pi1
switch - pi2
switch - tiny1
switch - tiny2
switch - tiny3
pikvm - tiny1
pikvm - tiny2
pikvm - tiny3

@enduml

@startuml Clusters

frame picluster {
    node pi1 {
        [zwavejs2mqtt]
        [etcd1]
    }
    node pi2 {
        [pikvm]
        [etcd2]
    }
}
frame tinycluster {
    node tiny1 {
        [etcd3]
        [control1]
        [worker1]
    }
    node tiny2 {
        [control2]
        [worker2]
    }
    node tiny3 {
        [control3]
        [worker3]
    }
}

frame "etcd cluster" {
    node "pi1" as pi1ref #line.dotted
    node "pi2" as pi2ref #line.dotted
    node "tiny1" as tiny1ref #line.dotted
}

frame "control plane and workers" {
    node "tiny1" as tiny1ref2 #line.dotted
    node "tiny2" as tiny2ref2 #line.dotted
    node "tiny3" as tiny3ref2 #line.dotted
}
pi1ref -- pi1
pi2ref -- pi2
tiny1ref -- tiny1
tiny1ref2 -- tiny1
tiny2ref2 -- tiny2
tiny3ref2 -- tiny3
pikvm -- tiny1
pikvm -- tiny2
pikvm -- tiny3

@enduml
