@startuml Layer 1 topology (today)

cloud isp
node ont as "fiber ONT"
node wan as "WAN router"
node firewall #line.dotted
node managed_switch as "managed switch"
node switch as "dumb switch"
node poe as "PoE switch"
node camera
node zwave as "z-wave controller"

frame lab {
    frame pis as "Pi cluster" {
        node pi1 as "Pi 1 (zwave)"
        node pi2 as "Pi 2 (kvm)"
    }
    frame x86 as "x86 cluster" {
        node tiny1
        node tiny2
        node tiny3
    }
}
frame WAPs {
    node wap1 as "WAP"
    node wap2 as "WAP"
    node wap3 as "WAP"
}



isp -- ont: fiber
ont -- wan
wan -- managed_switch
firewall -- managed_switch: one-legged
managed_switch - switch
managed_switch -- wap1: PoE
managed_switch -- wap2: PoE
managed_switch -- wap3: PoE
switch -- poe
switch -- pi1
switch -- pi2
switch -- tiny1
switch -- tiny2
switch -- tiny3
poe -- camera: passive PoE
pi1 -- zwave: usb
pi1 -- kvm
pi2 -- kvm #line.dashed
tiny1 -- kvm: w/ATX
tiny2 -- kvm
tiny3 -- kvm

@enduml

@startuml Layer 1 topology (future)

cloud isp
node ont as "fiber ONT"
node wan as "WAN router"
node firewall #line.dotted
node managed_switch as "managed switch"
node switch as "dumb switch"
node poe as "PoE switch"
node camera
node zwave as "z-wave controller"

frame lab {
    frame pis as "Pi cluster" {
        node pi1 as "Pi 1 (zwave)"
        node pi2 as "Pi 2 (kvm)"
    }
    frame x86 as "x86 cluster" {
        node tiny1
        node tiny2
        node tiny3
    }
}
frame WAPs {
    node wap1 as "WAP"
    node wap2 as "WAP"
    node wap3 as "WAP"
}



isp -- ont: fiber
ont -- wan
wan -- managed_switch
firewall -- managed_switch: one-legged
managed_switch - switch
managed_switch -- wap1: PoE
managed_switch -- wap2: PoE
managed_switch -- wap3: PoE
switch -- poe
switch -- pi1
switch -- pi2
switch -- tiny1
switch -- tiny2
switch -- tiny3
poe -- camera: passive PoE
pi1 -- zwave: usb
pi1 -- kvm
pi2 -- kvm #line.dashed
tiny1 -- kvm: w/ATX
tiny2 -- kvm
tiny3 -- kvm

@enduml