serviceType: "LoadBalancer"
service:
  externalIPs: 
  - 192.168.1.64
isClusterService: false

servers:
- zones:
  - zone: .
    scheme: dns://
  port: 53
  plugins:
  # Required to query kubernetes API for data
  - name: kubernetes
    parameters: cluster.local in-addr.arpa ip6.arpa
    configBlock: |-
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
      ttl 30
  # - name: mdns
  #   parameters: johntron.com
  - name: errors
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
    configBlock: |-
      lameduck 5s
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready
  # Serves a /metrics endpoint on :9153, required for serviceMonitor
  # - name: prometheus
  #   parameters: 0.0.0.0:9153
  - name: forward
    parameters: . /etc/resolv.conf
  - name: cache
    parameters: 30
  - name: loop
  - name: reload
  - name: loadbalance
  - name: log
  - name: k8s_external
    parameters: johntron.com
