
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  tag: "2022.7"

# additionalContainers:
#   - name: ts-sidecar
#     imagePullPolicy: Always
#     image: "ghcr.io/tailscale/tailscale:latest"
#     env:
#       # Store the state in a k8s secret
#     - name: TS_KUBE_SECRET
#       value: "tailscale-auth"
#     - name: TS_USERSPACE
#       value: "true"
#     - name: TS_AUTH_KEY
#       valueFrom:
#         secretKeyRef:
#           name: tailscale-auth
#           key: TS_AUTH_KEY
#           optional: true
#     securityContext:
#       runAsUser: 1000
#       runAsGroup: 1000
#       capabilities:
#         add:
#         - NET_ADMIN

strategy:
  type: Recreate

env: {}
  # TZ:

controller:
  type: statefulset
volumeClaimTemplates:
  - name: home-assistant
    accessMode: ReadWriteOnce
    size: 5Gi
    mountPath: /config

service:
  main:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.65
    externalIPs:
      - 192.168.1.65
    ports:
      http:
        port: 80
        targetPort: 8123

# Enable devices to be discoverable
hostNetwork: true

persistence:
  config:
    enabled: false
    type: pvc
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /config
