apiVersion: v1
kind: Service
metadata:
  name: workstation
  labels:
    app: workstation
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: workstation
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workstation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: workstation
        version: v1
    spec:
      containers:
      - name: workstation
        image: workstation
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: equipment
  labels:
    app: equipment
spec:
  ports:
  - port: 80
    name: tcp
  selector:
    app: equipment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: equipment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: equipment
        version: v1
    spec:
      containers:
      - name: equipment
        image: equipment
        ports:
        - containerPort: 80
