apiVersion: v1
kind: Service
metadata:
  name: composer
  labels:
    app: composer
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: composer
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: composer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: composer
        version: v1
    spec:
      containers:
      - name: composer
        image: composer
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: header
  labels:
    app: header
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: header
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: header
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: header
        version: v1
    spec:
      containers:
      - name: header
        image: header
        ports:
        - containerPort: 8080
